# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/metal-map-246806/olokotoh', '.']

# logsBucket: 'gs://olokotoh'
# options:
#   logging: 'LEGACY'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/metal-map-246806/olokotoh-loki', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/metal-map-246806/olokotoh-loki']


logsBucket: 'gs://olokotoh'
options:
  logging: 'LEGACY'

