steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/metal-map-246806/olokotoh', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/metal-map-246806/olokotoh']

# ... other build steps ...

options:
  logging: {'cloudBuilders': {'streaming': 'true'}}
logsBucket: 'gs://olokotoh'  # Update this line with your bucket name
