# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/metal-map-246806/olokotoh', '.']
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'gcr.io/metal-map-246806/olokotoh']

# options:
#   logging: {'cloudBuilders': {'streaming': 'true'}}
# logsBucket: 'gs://olokotoh' 
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/metal-map-246806/olokotoh', '.']

logsBucket: 'gs://olokotoh'
options:
  logging: 'LEGACY'
