# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/metal-map-246806/olokotoh', '.']

# logsBucket: 'gs://olokotoh'
# options:
#   logging: 'LEGACY'

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/my-bitnami-hosting/log-loki-test', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/my-bitnami-hosting/log-loki-test']


logsBucket: 'gs://cloudbuild-log-loki'
options:
  logging: 'LEGACY'

